### ISSUE TITLE
How do you create those beautiful Lamport diagrams?

### ISSUE THREAD

**Issue by kkppll-ss** [ChrisWhealy/DistributedSystemNotes#2]
I would like to write an article about distributed systems but could not find a good tool for those Lamport diagrams (like here https://github.com/ChrisWhealy/DistributedSystemNotes/blob/master/img/L16%20Paxos%20Phases.png). The diagrams in notes looks great! Can you tell me how you created them?

**Comment by bosdhill** [comment]
I'm not the author, but I've used draw.io to create Lamport diagrams. They look similar to the ones in Chris' notes.

**Comment by ChrisWhealy** [comment]
I don't know of any specific diagramming tool for drawing Lamport diagrams - I just used PowerPoint...  😃 

So I've now included the [Diagrams.pptx](https://github.com/ChrisWhealy/DistributedSystemNotes/blob/master/img/Diagrams.pptx) file.

To create a PNG image, select the relevant drawing objects, then right-click and select "Save as image".  This will then create a PNG file for you

Hope that helps

Chris W
